name: Maven CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Runs the Maven test phase on the project
  maven_test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"
          cache: maven

      - name: Test with Maven
        run: mvn test

      - name: Upload jacoco results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Jacoco coverage results
          path: target/site/jacoco

      - name: Cache build
        uses: actions/cache@v3
        with:
          key: cached-build-${{github.sha}}
          path: .

  # Uploads dependency graph to GitHub to receive Dependabot alerts
  update_dependency_graph:
    needs: [maven_test] # Ensures maven_test runs first
    runs-on: ubuntu-latest

    permissions:
      contents: write
      dependency-graph: write # Add permission for dependency graph updates

    steps:
      - name: Restore cached build
        uses: actions/cache@v3
        with:
          key: cached-build-${{github.sha}}
          path: .

      - name: Checkout repository
        uses: actions/checkout@v3 # Ensure the repository is checked out

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3
